# This workflow will build a golang project
name: Build
on:
  push:
    branches: [ "main" ]

env:
  TAG: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Get Go Dependencies
        run: go get -v -t -d ./...

      - name: Build the application
        run: |
          echo 'Building application version $TAG'
          go build -o yaaf-network-utils

      - name: Copy artifacts to docker build folder
        run: |
          cp -f ./yaaf-network-utils ./build/yaaf-network-utils

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./build
          push: true
          no-cache: true
          build-args: |
            VERSION_NUM=$TAG
          tags: |
            mottyc/yaaf-network-utils:${{ env.TAG }}
            mottyc/yaaf-network-utils:latest



